services:
    xen-sysmon:
        build:
            context: .
            args:
                - FEDORA_VER
        volumes:
            - .:/src:Z
            - ./.rpmbuild/RPMS/:/root/rpmbuild/RPMS/:Z
        working_dir: /src
        command: sh tools/build_rpm.sh
