from typing import Any


XEN_SCHEDULER_CREDIT: int
XEN_SCHEDULER_CREDIT2: int

class Error(RuntimeError): ...

class xc:
    def __init__(self, *args, **kwargs) -> None: ...
    def assign_device(self, *args, **kwargs) -> Any: ...
    def buildid(self, *args, **kwargs) -> Any: ...
    def cpupool_addcpu(self, *args, **kwargs) -> Any: ...
    def cpupool_create(self, *args, **kwargs) -> Any: ...
    def cpupool_destroy(self, *args, **kwargs) -> Any: ...
    def cpupool_freeinfo(self, *args, **kwargs) -> Any: ...
    def cpupool_getinfo(self, *args, **kwargs) -> Any: ...
    def cpupool_movedomain(self, *args, **kwargs) -> Any: ...
    def cpupool_removecpu(self, *args, **kwargs) -> Any: ...
    def deassign_device(self, *args, **kwargs) -> Any: ...
    def dom_set_memshr(self, *args, **kwargs) -> Any: ...
    def domain_create(self, *args, **kwargs) -> Any: ...
    def domain_destroy(self, *args, **kwargs) -> Any: ...
    def domain_destroy_hook(self, *args, **kwargs) -> Any: ...
    def domain_dumpcore(self, *args, **kwargs) -> Any: ...
    def domain_getinfo(self, *args, **kwargs) -> Any: ...
    def domain_iomem_permission(self, *args, **kwargs) -> Any: ...
    def domain_ioport_permission(self, *args, **kwargs) -> Any: ...
    def domain_irq_permission(self, *args, **kwargs) -> Any: ...
    def domain_max_vcpus(self, *args, **kwargs) -> Any: ...
    def domain_pause(self, *args, **kwargs) -> Any: ...
    def domain_resume(self, *args, **kwargs) -> Any: ...
    def domain_send_trigger(self, *args, **kwargs) -> Any: ...
    def domain_set_memmap_limit(self, *args, **kwargs) -> Any: ...
    def domain_set_target_mem(self, *args, **kwargs) -> Any: ...
    def domain_set_time_offset(self, *args, **kwargs) -> Any: ...
    def domain_set_tsc_info(self, *args, **kwargs) -> Any: ...
    def domain_sethandle(self, *args, **kwargs) -> Any: ...
    def domain_setmaxmem(self, *args, **kwargs) -> Any: ...
    def domain_shutdown(self, *args, **kwargs) -> Any: ...
    def domain_unpause(self, *args, **kwargs) -> Any: ...
    def evtchn_alloc_unbound(self, *args, **kwargs) -> Any: ...
    def evtchn_reset(self, *args, **kwargs) -> Any: ...
    def flask_access(self, *args, **kwargs) -> Any: ...
    def flask_context_to_sid(self, *args, **kwargs) -> Any: ...
    def flask_getenforce(self, *args, **kwargs) -> Any: ...
    def flask_load(self, *args, **kwargs) -> Any: ...
    def flask_setenforce(self, *args, **kwargs) -> Any: ...
    def flask_sid_to_context(self, *args, **kwargs) -> Any: ...
    def get_device_group(self, *args, **kwargs) -> Any: ...
    def getcpuinfo(self, *args, **kwargs) -> Any: ...
    def gnttab_hvm_seed(self, *args, **kwargs) -> Any: ...
    def hvm_get_param(self, *args, **kwargs) -> Any: ...
    def hvm_set_param(self, *args, **kwargs) -> Any: ...
    def numainfo(self, *args, **kwargs) -> Any: ...
    def pages_to_kib(self, *args, **kwargs) -> Any: ...
    def physdev_map_pirq(self, *args, **kwargs) -> Any: ...
    def physdev_pci_access_modify(self, *args, **kwargs) -> Any: ...
    def physinfo(self, *args, **kwargs) -> Any: ...
    def readconsolering(self, *args, **kwargs) -> Any: ...
    def sched_credit2_domain_get(self, *args, **kwargs) -> Any: ...
    def sched_credit2_domain_set(self, *args, **kwargs) -> Any: ...
    def sched_credit_domain_get(self, *args, **kwargs) -> Any: ...
    def sched_credit_domain_set(self, *args, **kwargs) -> Any: ...
    def sched_id_get(self, *args, **kwargs) -> Any: ...
    def send_debug_keys(self, *args, **kwargs) -> Any: ...
    def shadow_control(self, *args, **kwargs) -> Any: ...
    def shadow_mem_control(self, *args, **kwargs) -> Any: ...
    def test_assign_device(self, *args, **kwargs) -> Any: ...
    def topologyinfo(self, *args, **kwargs) -> Any: ...
    def vcpu_getinfo(self, *args, **kwargs) -> Any: ...
    def vcpu_setaffinity(self, *args, **kwargs) -> Any: ...
    def xeninfo(self, *args, **kwargs) -> Any: ...
