from typing import Any


class Error(RuntimeError): ...

class xs:
    def __init__(self, *args, **kwargs) -> None: ...
    def check_watch(self, *args, **kwargs) -> Any: ...
    def close(self, *args, **kwargs) -> Any: ...
    def fileno(self, *args, **kwargs) -> Any: ...
    def get_domain_path(self, *args, **kwargs) -> Any: ...
    def get_permissions(self, *args, **kwargs) -> Any: ...
    def introduce_domain(self, *args, **kwargs) -> Any: ...
    def ls(self, *args, **kwargs) -> Any: ...
    def mkdir(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    def read_watch(self, *args, **kwargs) -> Any: ...
    def release_domain(self, *args, **kwargs) -> Any: ...
    def resume_domain(self, *args, **kwargs) -> Any: ...
    def rm(self, *args, **kwargs) -> Any: ...
    def set_permissions(self, *args, **kwargs) -> Any: ...
    def set_target(self, *args, **kwargs) -> Any: ...
    def transaction_end(self, *args, **kwargs) -> Any: ...
    def transaction_start(self, *args, **kwargs) -> Any: ...
    def unwatch(self, *args, **kwargs) -> Any: ...
    def watch(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
