from _typeshed import Incomplete


class StreamError(Exception): ...
class RecordError(Exception): ...

class VerifyBase:
    info: Incomplete
    read: Incomplete
    def __init__(self, info, read) -> None: ...
    def rdexact(self, nr_bytes): ...
    def unpack_exact(self, fmt): ...
